### ISSUE TITLE
Any higher level wrappers?

### ISSUE THREAD

**Issue by rukai** [dropbox/fast_rsync#24]
Are there are any higher level rsync libraries, could be a wrapper of this library or another library.
I'm hoping for an api where I specify ssh keys, username and address to open a session and then specify a path to sync between the local and remote machines.
Unfortunately everything I've seen so far is either purely a CLI application or provides the same level of abstraction as librsync or fast_rsync.

If no such library exists feel free to just close this issue, thanks.

**Comment by goffrie** [comment]
There aren't any that I'm aware of.

You probably know this but the rsync delta format (i.e. what this library and `librsync` provide) is only a small part of the feature set of the `rsync` utility. I'd be surprised if there was a really featureful/well-maintained rsync clone in Rust today, so I'd probably just shell out to `rsync` - janky but probably good enough?
