### ISSUE TITLE
Stream API?

### ISSUE THREAD

**Issue by DmitrySoshnikov** [dropbox/fast_rsync#7]
I've two questions:

- Does this library support streaming API? Example: need to calculate deltas for large files (4GB+). From the examples I found all the delta, and signatures are memory vectors
- Is this library compatible with the original `librsync` in C++?

In general would be great having more usage examples in this repo. Thanks!

**Comment by goffrie** [comment]
Sorry, I completely missed this issue!
> Does this library support streaming API? Example: need to calculate deltas for large files (4GB+). From the examples I found all the delta, and signatures are memory vectors

It doesn't. This was a choice to make the library simpler, as in our use case we only ever need to operate on buffers that are already in-memory.

> Is this library compatible with the original librsync in C++?

It isn't. `librsync` has a much more powerful and complex API that this library wouldn't be able to emulate.
